spring.application.name=iprac
server.port=8080
# Gemini API Configuration
gemini.api.key=AIzaSyA2uhq-oUgJWf_6_mj9BV-eD8H_6vZoYuI
gemini.api.url=https://generativelanguage.googleapis.com/v1beta/models/gemini-2.0-flash:generateContent
